# Example Pipeline Build Script that does a simple copy to an artifact directory
# You can add much more complex scripts yourself later once you get this working

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo About to list all contents of current directory:
    ls -al
    echo About to list contents of drop location:
    ls -al $(Build.ArtifactStagingDirectory)
    echo About to copy the artifact elements to the drop location:
    mv LICENSE.txt $(Build.ArtifactStagingDirectory)
    mv calls-to-modules $(Build.ArtifactStagingDirectory)
    mv modules $(Build.ArtifactStagingDirectory)
    echo About to list contents of Artifact Staging Directory
    ls -al $(Build.ArtifactStagingDirectory)
  displayName: 'Run a multi-line script'
